refactor: update application name and improve configuration files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,22 +5,45 @@ on:
     branches: [ "master" ]
 
 jobs:
-  build:
-
+  format-checker:
+    name: Format Checker
     runs-on: ubuntu-slim
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v6
+      - name: Set up JDK 21
+        uses: actions/setup-java@v5
+        with:
+          java-version: '21'
+          distribution: 'microsoft'
+          cache: 'gradle'
+      - name: Check Formatting
+        run: ./gradlew ktlintCheck
 
+  build:
+    name: Build and Analyze
+    runs-on: ubuntu-slim
+    needs: format-checker
     steps:
     - name: Checkout repository
       uses: actions/checkout@v6
       with:
         fetch-depth: 0
-
     - name: Set up JDK 21
       uses: actions/setup-java@v5
       with:
         java-version: '21'
         distribution: 'microsoft'
         cache: 'gradle'
-
-    - name: Build with Gradle
-      run: ./gradlew build
+    - name: Build and analyze
+      run: ./gradlew build sonar --info
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v6
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        commit: ${{github.event.workflow_run.head_sha}}
+        report_paths: '**/test/TEST-*.xml'
+        require_tests: true
+        annotate_notice: false
